### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Ferdyverse** [jmt-gh/audiobookshelf-sonos#7]
Hello,

I am not able to get a valid SSL connection. I always get the following error:

```
curl https://audiosonos.xxxxxx.net -vvv
*   Trying 192.168.1.9:443...
* TCP_NODELAY set
* Connected to audiosonos.xxxxxxxx.net (192.168.1.9) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, unrecognized name (624):
* error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
* Closing connection 0
curl: (35) error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
```
In Chrome the error is `ERR_HTTP2_PROTOCOL_ERROR`
I can access all my other URLs behind my reverse proxy but not this one. Any ideas on how to fix this issue? Is there a URL rewrite hidden in the code to a hardcoded URL?

The direct connection to the service is working:
```
curl http://192.168.1.24:8081/manifest
{"schemaVersion":"1.0","endpoints":[{"type":"reporting","uri":"https://audiosonos.xxxxxxxx.net/playback/v2.1/report"}]
```

**Comment by dubwoc** [comment]
This seems more like a configuration issue on your part given audiobookshelf-sonos is responding to unencrypted traffic directly. 


I am assuming you are running your reverse proxy on 192.168.1.9, it doesn't look like you have a cert provisioned there. That being said it may be easier if you post your reverse proxy config or at least the pertinent part.

**Comment by Ferdyverse** [comment]
Yes, 192.168.1.9 is my reverse proxy. Here is my config: 

![Screenshot_20240130-065650~2.png](https://github.com/jmt-gh/audiobookshelf-sonos/assets/1213924/ebb3d869-f304-41a7-9206-f87191cb33c0)

![Screenshot_20240130-065748~2.png](https://github.com/jmt-gh/audiobookshelf-sonos/assets/1213924/37b58ad1-a155-44e0-b7c6-4e4225ba3b69)

![Screenshot_20240130-065735~2.png](https://github.com/jmt-gh/audiobookshelf-sonos/assets/1213924/119162e2-2ec7-4880-af52-1d6dd1dcfbdd)


I currently have about 30 urls configured like this and they are all working fine.

**Comment by dubwoc** [comment]
Good that you have a bunch of other ones working properly, but I am still thinking there is a misconfiguration somewhere in your chain. Even without the service running you should be able to view the TLS handshake from your reverse proxy with curl -v \<url> that then ends with a 502. 

Are you able to do that?

**Comment by Ferdyverse** [comment]
I just rebuild the docker container. Now everything is working.... Sry for the issue... I do not understand what happened...
